### PR TITLE
GitHub orgname

### PR DESCRIPTION
**Pull request by kkaempf**
Second piece of @dmacvicar's pull request. Rebased to current master, split to smaller pieces

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
line 82 in `lib/nailed/github.rb` needs an update as well (the org must be passed)

**Comment by MaximilianMeister** [comment]
AFAICS the navigation in `views/layout.haml` still points to the old route without the organization. that would need to be changed as well

**Comment by kkaempf** [comment]
Yes, but lets take one step after another ;-)

**Comment by MaximilianMeister** [comment]
okay, i will fix the layout then :)

thanks!

**Comment by kkaempf** [comment]
Thanks for merging. Stay tuned for more fixes in this area ;-)

**Pull request merged**
